services:
  tool:
    container_name: bizgroup-tool-${ENV}
    restart: always
    image: sangnv/bizgroup-thunder:x86
    volumes:
      - .:/tool
    working_dir: /tool
    ports:
      - "3000-3005:3000-3005"

  postgres:
    container_name: bizgroup-tool-${ENV}
    image: postgres:latest
    environment:
      - POSTGRES_USER=lit
      - POSTGRES_PASSWORD=lit
      - POSTGRES_DB=master
    ports:
      - 54321:5432

  redis:
    image: redis:latest
    ports:
      - 63791:6379

  collector:
    image: otel/opentelemetry-collector-contrib:0.120.0
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
