services:
  tool:
    container_name: ${GROUP_NAME}-tool-${ENV}
    restart: always
    image: sangnv/${GROUP_NAME}-thunder:x86
    volumes:
      - .:/tool
    working_dir: /tool
    ports:
      - "3000-3005:3000-3005"
