// Code generated by mockery v2.53.0. DO NOT EDIT.

package kafka

import mock "github.com/stretchr/testify/mock"

// MockConsumerOption is an autogenerated mock type for the ConsumerOption type
type MockConsumerOption struct {
	mock.Mock
}

type MockConsumerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerOption) EXPECT() *MockConsumerOption_Expecter {
	return &MockConsumerOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockConsumerOption) Execute(_a0 *consumerConfig) {
	_m.Called(_a0)
}

// MockConsumerOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConsumerOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *consumerConfig
func (_e *MockConsumerOption_Expecter) Execute(_a0 interface{}) *MockConsumerOption_Execute_Call {
	return &MockConsumerOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockConsumerOption_Execute_Call) Run(run func(_a0 *consumerConfig)) *MockConsumerOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*consumerConfig))
	})
	return _c
}

func (_c *MockConsumerOption_Execute_Call) Return() *MockConsumerOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConsumerOption_Execute_Call) RunAndReturn(run func(*consumerConfig)) *MockConsumerOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockConsumerOption creates a new instance of MockConsumerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerOption {
	mock := &MockConsumerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
