// Code generated by mockery v2.53.0. DO NOT EDIT.

package kafka

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockConsumeHandler is an autogenerated mock type for the ConsumeHandler type
type MockConsumeHandler struct {
	mock.Mock
}

type MockConsumeHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumeHandler) EXPECT() *MockConsumeHandler_Expecter {
	return &MockConsumeHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, msg
func (_m *MockConsumeHandler) Execute(ctx context.Context, msg ConsumerMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ConsumerMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumeHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConsumeHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - msg ConsumerMessage
func (_e *MockConsumeHandler_Expecter) Execute(ctx interface{}, msg interface{}) *MockConsumeHandler_Execute_Call {
	return &MockConsumeHandler_Execute_Call{Call: _e.mock.On("Execute", ctx, msg)}
}

func (_c *MockConsumeHandler_Execute_Call) Run(run func(ctx context.Context, msg ConsumerMessage)) *MockConsumeHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ConsumerMessage))
	})
	return _c
}

func (_c *MockConsumeHandler_Execute_Call) Return(_a0 error) *MockConsumeHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumeHandler_Execute_Call) RunAndReturn(run func(context.Context, ConsumerMessage) error) *MockConsumeHandler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumeHandler creates a new instance of MockConsumeHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumeHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumeHandler {
	mock := &MockConsumeHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
