// Code generated by mockery v2.53.0. DO NOT EDIT.

package kafka

import mock "github.com/stretchr/testify/mock"

// MockProducerOption is an autogenerated mock type for the ProducerOption type
type MockProducerOption struct {
	mock.Mock
}

type MockProducerOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducerOption) EXPECT() *MockProducerOption_Expecter {
	return &MockProducerOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MockProducerOption) Execute(_a0 *producerConfig) {
	_m.Called(_a0)
}

// MockProducerOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockProducerOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *producerConfig
func (_e *MockProducerOption_Expecter) Execute(_a0 interface{}) *MockProducerOption_Execute_Call {
	return &MockProducerOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MockProducerOption_Execute_Call) Run(run func(_a0 *producerConfig)) *MockProducerOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*producerConfig))
	})
	return _c
}

func (_c *MockProducerOption_Execute_Call) Return() *MockProducerOption_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProducerOption_Execute_Call) RunAndReturn(run func(*producerConfig)) *MockProducerOption_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMockProducerOption creates a new instance of MockProducerOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducerOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducerOption {
	mock := &MockProducerOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
